import 'dotenv/config';
import { drizzle } from 'drizzle-orm/neon-http';
import { neon } from '@neondatabase/serverless';
import * as schema from './schema';

const sql = neon(process.env.DATABASE_URL!);
const db = drizzle(sql, { schema });

async function seed() {
  console.log('🌱 Starting database seeding...');

  try {
    console.log('📦 Creating categories...');
    const categories = await db.insert(schema.category).values([
      {
        id: 'cat-1',
        name: 'Clothing',
        nameAr: 'حوايج',
        slug: 'clothing',
        description: 'Fashion and clothing items',
        displayOrder: 1,
        isActive: true,
      },
      {
        id: 'cat-2',
        name: 'Accessories',
        nameAr: 'إكسسوارات',
        slug: 'accessories',
        description: 'Fashion accessories',
        displayOrder: 2,
        isActive: true,
      },
      {
        id: 'cat-3',
        name: 'Shoes',
        nameAr: 'صبّاط',
        slug: 'shoes',
        description: 'Footwear collection',
        displayOrder: 3,
        isActive: true,
      },
      {
        id: 'cat-4',
        name: 'Electronics',
        nameAr: 'إلكترونيات',
        slug: 'electronics',
        description: 'Electronic devices and gadgets',
        displayOrder: 4,
        isActive: true,
      },
      {
        id: 'cat-5',
        name: 'Home & Living',
        nameAr: 'دار و معيشة',
        slug: 'home-living',
        description: 'Home decor and living essentials',
        displayOrder: 5,
        isActive: true,
      },
    ]).returning();
    console.log(`✅ Created ${categories.length} categories`);

    console.log('👕 Creating products...');
    const products = await db.insert(schema.product).values([
      {
        id: 'prod-1',
        name: 'Classic White T-Shirt',
        nameAr: 'تريكو أبيض كلاسيك',
        slug: 'classic-white-tshirt',
        description: 'Premium quality cotton t-shirt, perfect for everyday wear',
        descriptionAr: 'تريكو قطن جودة عالية، مثالي للإستعمال اليومي',
        price: '15.00',
        compareAtPrice: '25.00',
        costPrice: '8.00',
        sku: 'TSH-WHT-001',
        stock: 50,
        images: ['/images/products/tshirt-white.jpg', '/images/products/tshirt-white-2.jpg'],
        categoryId: 'cat-1',
        isActive: true,
        isFeatured: true,
        isNew: true,
        viewCount: 0,
      },
      {
        id: 'prod-2',
        name: 'Denim Jacket',
        nameAr: 'فيست جينز',
        slug: 'denim-jacket',
        description: 'Stylish denim jacket for all seasons',
        descriptionAr: 'فيست جينز أنيق لكل الفصول',
        price: '45.00',
        compareAtPrice: '60.00',
        costPrice: '25.00',
        sku: 'JKT-DNM-001',
        stock: 30,
        images: ['/images/products/jacket-denim.jpg'],
        categoryId: 'cat-1',
        isActive: true,
        isFeatured: true,
        isNew: false,
        viewCount: 0,
      },
      {
        id: 'prod-3',
        name: 'Leather Wallet',
        nameAr: 'محفظة جلد',
        slug: 'leather-wallet',
        description: 'Genuine leather wallet with multiple card slots',
        descriptionAr: 'محفظة جلد طبيعي مع أماكن متعددة للبطاقات',
        price: '20.00',
        compareAtPrice: '35.00',
        costPrice: '12.00',
        sku: 'ACC-WLT-001',
        stock: 100,
        images: ['/images/products/wallet-leather.jpg'],
        categoryId: 'cat-2',
        isActive: true,
        isFeatured: false,
        isNew: true,
        viewCount: 0,
      },
      {
        id: 'prod-4',
        name: 'Sports Sneakers',
        nameAr: 'سنيكرز رياضية',
        slug: 'sports-sneakers',
        description: 'Comfortable sports sneakers for daily activities',
        descriptionAr: 'سنيكرز رياضية مريحة للإستعمال اليومي',
        price: '35.00',
        compareAtPrice: '50.00',
        costPrice: '20.00',
        sku: 'SHO-SNK-001',
        stock: 40,
        images: ['/images/products/sneakers-sports.jpg', '/images/products/sneakers-sports-2.jpg'],
        categoryId: 'cat-3',
        isActive: true,
        isFeatured: true,
        isNew: false,
        viewCount: 0,
      },
      {
        id: 'prod-5',
        name: 'Wireless Earbuds',
        nameAr: 'سماعات لاسلكية',
        slug: 'wireless-earbuds',
        description: 'Premium wireless earbuds with noise cancellation',
        descriptionAr: 'سماعات لاسلكية فاخرة مع عزل الضوضاء',
        price: '40.00',
        compareAtPrice: '60.00',
        costPrice: '22.00',
        sku: 'ELC-EAR-001',
        stock: 60,
        images: ['/images/products/earbuds-wireless.jpg'],
        categoryId: 'cat-4',
        isActive: true,
        isFeatured: true,
        isNew: true,
        viewCount: 0,
      },
      {
        id: 'prod-6',
        name: 'Smart Watch',
        nameAr: 'ساعة ذكية',
        slug: 'smart-watch',
        description: 'Feature-rich smartwatch with health tracking',
        descriptionAr: 'ساعة ذكية بميزات متعددة لتتبع الصحة',
        price: '80.00',
        compareAtPrice: '120.00',
        costPrice: '45.00',
        sku: 'ELC-WTH-001',
        stock: 25,
        images: ['/images/products/watch-smart.jpg'],
        categoryId: 'cat-4',
        isActive: true,
        isFeatured: true,
        isNew: true,
        viewCount: 0,
      },
      {
        id: 'prod-7',
        name: 'Decorative Cushion Set',
        nameAr: 'طقم وسائد تزيينية',
        slug: 'decorative-cushion-set',
        description: 'Set of 4 decorative cushions for your living room',
        descriptionAr: 'طقم 4 وسائد تزيينية للصالون',
        price: '25.00',
        compareAtPrice: '40.00',
        costPrice: '14.00',
        sku: 'HOM-CSH-001',
        stock: 35,
        images: ['/images/products/cushions-set.jpg'],
        categoryId: 'cat-5',
        isActive: true,
        isFeatured: false,
        isNew: false,
        viewCount: 0,
      },
      {
        id: 'prod-8',
        name: 'Sunglasses',
        nameAr: 'نظارات شمسية',
        slug: 'sunglasses',
        description: 'Stylish UV protection sunglasses',
        descriptionAr: 'نظارات شمسية أنيقة مع حماية من الأشعة',
        price: '18.00',
        compareAtPrice: '30.00',
        costPrice: '10.00',
        sku: 'ACC-SUN-001',
        stock: 70,
        images: ['/images/products/sunglasses.jpg'],
        categoryId: 'cat-2',
        isActive: true,
        isFeatured: false,
        isNew: true,
        viewCount: 0,
      },
      {
        id: 'prod-9',
        name: 'Casual Backpack',
        nameAr: 'حقيبة ظهر كاجوال',
        slug: 'casual-backpack',
        description: 'Spacious backpack perfect for daily use',
        descriptionAr: 'حقيبة ظهر واسعة مثالية للإستعمال اليومي',
        price: '30.00',
        compareAtPrice: '45.00',
        costPrice: '18.00',
        sku: 'ACC-BKP-001',
        stock: 45,
        images: ['/images/products/backpack-casual.jpg'],
        categoryId: 'cat-2',
        isActive: true,
        isFeatured: true,
        isNew: false,
        viewCount: 0,
      },
      {
        id: 'prod-10',
        name: 'Cotton Hoodie',
        nameAr: 'هودي قطن',
        slug: 'cotton-hoodie',
        description: 'Comfortable cotton hoodie for casual wear',
        descriptionAr: 'هودي قطن مريح للإستعمال الكاجوال',
        price: '28.00',
        compareAtPrice: '40.00',
        costPrice: '16.00',
        sku: 'CLO-HOD-001',
        stock: 55,
        images: ['/images/products/hoodie-cotton.jpg', '/images/products/hoodie-cotton-2.jpg'],
        categoryId: 'cat-1',
        isActive: true,
        isFeatured: false,
        isNew: true,
        viewCount: 0,
      },
      {
        id: 'prod-11',
        name: 'Running Shoes',
        nameAr: 'صبّاط رياضة',
        slug: 'running-shoes',
        description: 'Professional running shoes with extra cushioning',
        descriptionAr: 'صبّاط رياضة إحترافي مع توسيد إضافي',
        price: '55.00',
        compareAtPrice: '75.00',
        costPrice: '32.00',
        sku: 'SHO-RUN-001',
        stock: 30,
        images: ['/images/products/shoes-running.jpg'],
        categoryId: 'cat-3',
        isActive: true,
        isFeatured: true,
        isNew: true,
        viewCount: 0,
      },
      {
        id: 'prod-12',
        name: 'Laptop Sleeve',
        nameAr: 'حافظة لابتوب',
        slug: 'laptop-sleeve',
        description: 'Protective sleeve for 15-inch laptops',
        descriptionAr: 'حافظة حماية للابتوب 15 بوصة',
        price: '22.00',
        compareAtPrice: '35.00',
        costPrice: '13.00',
        sku: 'ACC-LAP-001',
        stock: 40,
        images: ['/images/products/laptop-sleeve.jpg'],
        categoryId: 'cat-2',
        isActive: true,
        isFeatured: false,
        isNew: false,
        viewCount: 0,
      },
    ]).returning();
    console.log(`✅ Created ${products.length} products`);

    console.log('🎁 Creating random boxes...');
    const randomBoxes = await db.insert(schema.randomBox).values([
      {
        id: 'box-1',
        name: 'Mystery Box 10',
        nameAr: 'صندوق المفاجآت 10',
        description: 'Get products worth more than 10 TND',
        descriptionAr: 'احصل على منتجات بقيمة أكثر من 10 دينار',
        amount: '10.00',
        minValue: '15.00',
        maxValue: '30.00',
        colorGradient: 'from-blue-500 to-blue-600',
        icon: '🎁',
        displayOrder: 1,
        isActive: true,
        stock: 100,
        soldCount: 0,
      },
      {
        id: 'box-2',
        name: 'Mystery Box 20',
        nameAr: 'صندوق المفاجآت 20',
        description: 'Get products worth more than 20 TND',
        descriptionAr: 'احصل على منتجات بقيمة أكثر من 20 دينار',
        amount: '20.00',
        minValue: '30.00',
        maxValue: '50.00',
        colorGradient: 'from-purple-500 to-purple-600',
        icon: '🎉',
        displayOrder: 2,
        isActive: true,
        stock: 100,
        soldCount: 0,
      },
      {
        id: 'box-3',
        name: 'Mystery Box 50',
        nameAr: 'صندوق المفاجآت 50',
        description: 'Get products worth more than 50 TND',
        descriptionAr: 'احصل على منتجات بقيمة أكثر من 50 دينار',
        amount: '50.00',
        minValue: '75.00',
        maxValue: '120.00',
        colorGradient: 'from-pink-500 to-pink-600',
        icon: '✨',
        displayOrder: 3,
        isActive: true,
        stock: 100,
        soldCount: 0,
      },
    ]).returning();
    console.log(`✅ Created ${randomBoxes.length} random boxes`);

    console.log('✨ Database seeding completed successfully!');
    console.log(`📊 Summary:`);
    console.log(`   - Categories: ${categories.length}`);
    console.log(`   - Products: ${products.length}`);
    console.log(`   - Random Boxes: ${randomBoxes.length}`);
    console.log('');
    console.log('🚀 You can now view your data using: bun run db:studio');
    
  } catch (error) {
    console.error('❌ Error seeding database:', error);
    process.exit(1);
  }
}

seed()
  .then(() => {
    console.log('✅ Seeding finished!');
    process.exit(0);
  })
  .catch((error) => {
    console.error('❌ Seeding failed:', error);
    process.exit(1);
  });

